language: php

php:
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - hhvm

before_script:
    - composer require phpunit/phpunit
    - composer update

matrix:
    allow_failures:
        - php: hhvm

notifications:
    email: true
