language: php

php:
    - 5.5
    - 7.0
    - 7.1
    - hhvm

matrix:
    allow_failures:
        - php: hhvm

before_script:
    - composer self-update
    - composer install

script:
    - echo "Running PHPUnit Tests"
    - php vendor/bin/phpunit --coverage-text --colors=never --configuration ./build/phpunit.xml

notifications:
    email: false
